import { defineStyleConfig } from '@chakra-ui/react'

export default defineStyleConfig({
  baseStyle: {
    fontFamily: 'inherit',
    _hover: {}
  },
  sizes: {},
  variants: {
    'dashed': ({ colorMode }) => ({
      variant: 'dashed',
      color: colorMode === 'dark' ? 'white' : 'gray.400',
      fontSize: '1.2rem',
      textAlign: 'start',
      fontWeight: '400',
      padding: '0.5rem 1.5rem',
      borderRadius: '10rem',
      height: '3rem',
      wordBreak: 'break-word',
      border: '1px dashed',
      borderColor: 'gray.150',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      lineHeight: '1.2rem',
    }),
    'group-dropdowns': ({ colorMode }) => ({
      padding: '1.3rem',
      borderRadius: '0.6rem',
      bgColor: colorMode === 'dark' ? 'darcula.300' : 'gray.50',
      height: '3.4rem',
      color:  colorMode === 'dark' ? 'white' : 'gray.800',
      fontWeight: 500,
      fontSize: '1.2rem',
    }),
    'group-dropdowns-outline': ({ colorMode }) => ({
      paddingLeft: '1.3rem',
      paddingRight: '1.3rem',
      borderRadius: '1rem',
      backgroundColor: colorMode === 'dark' ? 'darcula.300' : 'white',
      border: '1px solid',
      borderColor: colorMode === 'dark' ? 'darcula.400' : 'gray.100',
      height: '3.4rem',
      color: colorMode === 'dark' ? 'white' : 'gray.800',
      fontWeight: 500,
      fontSize: '1.2rem',
    }),
    'dropdown-item': ({ colorMode }) => ({
      display: 'inline-block !important',
      minH: '3.4rem',
      color: colorMode === 'dark' ? 'white' : 'gray.800',
      fontWeight: '500',
      fontSize: '1.2rem',
      textAlign: 'left',
      _hover: { bgColor: colorMode === 'dark' ? 'darcula.400' : 'gray.50' },
      _focus: { bgColor: colorMode === 'dark' ? 'darcula.400' : 'gray.50' },
    }),
    'select-anchor-inside-input': ({ colorMode }) => ({
      minW: { sm: '160px', base: '100px' },
      display: 'flex',
      alignItems: 'center',
      fontWeight: '500',
      bgColor: colorMode === 'dark' ? 'darcula.300' : 'white',
      borderRadius: 'none',
      borderTopLeftRadius: '1rem',
      borderBottomLeftRadius: '1rem',
      color: colorMode === 'dark' ? 'white' : 'gray.800',
      cursor: 'pointer',
      paddingX: { sm: '2rem', base: '1rem' },
      borderRight: colorMode === 'dark' ? '0.1rem solid var(--chakra-colors-darcula-400)' : '0.1rem solid var(--chakra-colors-gray-100)',
      height: 'full',
    }),
    'nav-switcher': (props) => ({
      position: 'absolute',
      top: '6.2rem',
      right: '-1.4rem',
      width: '2.8rem',
      height: '2.8rem',
      borderRadius: '0.8rem',
      backgroundColor: props.colorMode === 'dark' ? 'darcula.700' : 'white',
      border: '0.1rem solid',
      borderColor: props.colorMode === 'dark' ? 'darcula.400' : 'gray.100',
      zIndex: 20,
      cursor: 'pointer',
    }),
    'gray': ({ colorMode }) => ({
      padding: '1.3rem',
      borderRadius: '1rem',
      backgroundColor: colorMode === 'dark' ? 'darcula.400' : 'gray.50',
      height: '3.4rem',
      color: colorMode === 'dark' ? 'white' : 'gray.800',
      fontWeight: 500,
      fontSize: '1.2rem',
      _hover: {
        backgroundColor: colorMode === 'dark' ? 'darcula.500' : 'gray.100',
      },
    }),
    'brand-transparency': ({ colorMode }) => ({
      appearance: 'none',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '4.4rem',
      border: 'none',
      borderRadius: '1rem',
      background: colorMode === 'dark' ? 'brand.500' : '#ff008c0d',
      color: colorMode === 'dark' ? 'white' : 'brand.500',
      fontSize: '1.4rem',
      fontWeight: 400,
      _hover: {
        background: colorMode === 'dark' ? 'brand.600' : '#ff008c1a',
      }
    }),
    'timeslot-btn':  ({ colorMode }) => ({
      padding: '0.6rem 0.8rem',
      border: '1px solid',
      borderRadius: '0',
      marginInlineEnd: '-1px',
      backgroundColor: colorMode === 'dark' ? 'darcula.300' : 'white',
      borderColor: colorMode === 'dark' ? 'darcula.400' : 'gray.100',
      color: colorMode === 'dark' ? 'gray.100' : 'gray.800',
      fontSize: '1.2rem',
      fontWeight: 'normal',
      lineHeight: '1.8rem',
      height: 'full',
      _selected: {
        bgColor: colorMode === 'dark' ? 'darcula.400' : 'gray.50',
      }
    }),
  },
  defaultProps: {},
})